## **1. Set connection to Google Drive**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Change present working directory

In [3]:
%cd /content/drive/MyDrive/MasterThesis

/content/drive/MyDrive/MasterThesis

## **2. Git Handling**

In [4]:
!git config --global user.email "gabriel.peier@stud.hslu.ch"

In [5]:
username = "Icelander169"
git_token = "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"
repository = "MasterThesis"

In [6]:
# !git init Scripts

In [7]:
%cd Scripts

/content/drive/MyDrive/MasterThesis/Scripts

In [ ]:
!git add . # adding changes for commitment

In [185]:
!git status

On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   01_Reading_Data.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [10]:
# !git remote add origin https://{git_token}@github.com/{username}/{repository}.git
# !git remote -v

In [182]:
!git commit -m "cleaning stop count list added"

[master 09cae4c] cleaning stop count list added
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 01_Reading_Data.ipynb (82%)

In [184]:
!git push origin

error: src refspec test does not match any.
error: failed to push some refs to 'https://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@github.com/Icelander169/MasterThesis.git'

In [186]:
!git checkout -b test

M	01_Reading_Data.ipynb
Switched to a new branch 'test'

## **3. Importing packages**

In [13]:
import pandas as pd
import numpy as np
# import scanpy as sc
from scipy.io import mminfo,mmread # handlings sparse matrices

## **4. Loading Data**

In [144]:
ga_hta = pd.read_excel("../Data/Raw/ga_hta_list.xlsx")
ga_hta

,Jahr_An_Anno,PLZ_NPA,GA_AG,GA_AG_flag,HTA_ADT_meta-prezzo,HTA_ADT_meta-prezzo_flag
0,2012,1000,72.0,NaN,976.0,NaN
1,2012,1003,744.0,NaN,3195.0,NaN
2,2012,1004,1919.0,NaN,8167.0,NaN
3,2012,1005,860.0,NaN,4021.0,NaN
4,2012,1006,1279.0,NaN,5366.0,NaN
...,...,...,...,...,...,...
28678,2020,9652,55.0,NaN,283.0,NaN
28679,2020,9655,12.7,1.0,95.0,NaN
28680,2020,9656,21.0,NaN,185.0,NaN
28681,2020,9657,36.0,NaN,235.0,NaN
28682,2020,9658,71.0,NaN,403.0,NaN

In [148]:
population = pd.read_excel('../Data/Raw/population.xlsx')
population

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,su-d-01.02.03.07,"Ständige Wohnbevölkerung nach Postleitzahl, Staatsangehörigkeitskategorie, Geschlecht, Fünfjahresaltersklasse und Zivilstand, am 31.12.2020",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,Postleitzahl,NaN,Staatsangehörigkeitskategorie,NaN,Geschlecht,NaN,Fünfjahresklasse,NaN,NaN,NaN,...,NaN,NaN,NaN,Zivilstand 1,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,Schweiz,Ausland,Mann,Frau,0-4,5-9,10-14,15-19,...,80-84,85-89,90 und mehr,Ledig,Verheiratet,Verwitwet,Geschieden,Unverheiratet,In eingetrage-ner Partner-schaft,Aufgelöste Partnerschaft
2,Schweiz,8670300,6459512,2210788,4302599,4367701,437118,439685,429468,420030,...,227086,147174,84029,3903333,3588894,403471,751735,617,19022,2981
3,1000,3991,2379,1612,1957,2034,208,179,219,559,...,50,27,14,2378,1307,81,217,0,7,1
4,1003,6528,3555,2973,3290,3238,265,187,190,206,...,85,55,56,4101,1628,178,556,1,59,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,1 Serienbruch ab 2014: Exkl. „ohne Angabe“,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3186,Quelle: STATPOP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3187,© BFS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3189,"Auskunft: Bundesamt für Statistik (BFS), Sekti...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
cars = pd.read_csv('../Data/Raw/cars_per_municipality.csv', sep = ";", encoding = 'latin-1')
cars

,Gemeinde,Fahrzeuggruppe,Treibstoff,2015,2016,2017,2018,2019,2020,2021
0,1 Aeugst am Albis,Personenwagen,Benzin,845,822,815,816,809,804,792
1,1 Aeugst am Albis,Personenwagen,Diesel,288,306,316,318,326,329,320
2,1 Aeugst am Albis,Personenwagen,Benzin-elektrisch: Normal-Hybrid,13,18,16,20,22,30,43
3,1 Aeugst am Albis,Personenwagen,Benzin-elektrisch: Plug-in-Hybrid,0,1,2,7,7,12,20
4,1 Aeugst am Albis,Personenwagen,Diesel-elektrisch: Normal-Hybrid,0,0,2,2,3,2,5
...,...,...,...,...,...,...,...,...,...,...
151405,6810 La Baroche,Anhänger,Diesel-elektrisch: Plug-in-Hybrid,0,0,0,0,0,0,0
151406,6810 La Baroche,Anhänger,Elektrisch,0,0,0,0,0,0,0
151407,6810 La Baroche,Anhänger,Wasserstoff,0,0,0,0,0,0,0
151408,6810 La Baroche,Anhänger,Gas (mono- und bivalent),0,0,0,0,0,0,0
151409,6810 La Baroche,Anhänger,Anderer,180,190,202,202,209,216,227

In [150]:
stations = pd.read_excel('../Data/Raw/stations_list_bav.xlsx')
stations

,Dst-Nr85,Ld,Dst-Nr,KZ,Name,Länge,Name lang,Dst-Abk,BP,VP,...,Ortschaft,Gde-Nr,Gemeinde,Kt.,E-Koord.,N-Koord.,Höhe,Bemerkungen,Karte,Karte.1
0,N° sv.85,py,N° sv.,Cc,Nom (ordre alphab.),Longueur,Nom long,Sigle sv.,PE,PT,...,Localité,N° commune,Commune,Ct.,Coord. E,Coord. N,Altitude,Remarque,Carte,Carte
1,Dienststellen-\nNummer siebenstellig,Ländercode,Dienststellen-\nNummer (85...),Kontrollziffer (o.Ld),Name \n(Dst-Bezeichnung),Länge (Name),Name lang \n(50 Zeichen),Dienststellen-\nAbkürzung,Betriebspunkt des Fahrplans,Haltestelle,...,Ortschaft,Gemeinde-\nNummer BFS,Gemeinde,Kanton,E-Koordinate,N-Koordinate,Höhe m ü.M.,Bemerkungen,Hyperlink auf \nmapsearch.ch,Hyperlink auf \nmap.geo.admin.ch
2,NaN,NaN,NaN,NaN,"Datenstand am 24.02.2022, Auszug für 24.02.2022",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
3,8506013,85,6013,7,Aadorf,6,NaN,AD,*,Ho,...,Aadorf,4551,Aadorf,TG,2710378,1260736,528,NaN,▲,▲
4,8573363,85,73363,4,"Aadorf, Bahnhof",15,NaN,NaN,*,Ho,...,Aadorf,4551,Aadorf,TG,2710335,1260768,528,NaN,▲,▲
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
49999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
50001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
50002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲

In [151]:
stop_count = pd.read_csv('../Data/Raw/stop_count.csv', sep = ",", encoding="latin-1")
stop_count

        FP_ID,"TU_CODE","TU_BEZEICHNUNG","TU_ABKUERZUNG","FARTNUMMER","BPUIC","BP_BEZEICHNUNG","BP_ABKUERZUNG","KANTON","SLOID","VM_ART","FAHRTAGE","AB_ZEIT_KB","AN_ZEIT_KB","RICHTUNG_TEXT_AGGREGIERT","END_BP_BEZEICHNUNG","LINIE","BP_ID"
0        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
1        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
2        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
3        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
4        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
...                                                    ...
1048570  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048571  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048572  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048573  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048574  2022,"764","Automobiles MBC","MBC Auto",4047,8...

[1048575 rows x 1 columns]

In [152]:
town_directory = pd.read_csv('../Data/Raw/town_directory.csv')
town_directory

,Ortschaftsname,PLZ,Zusatzziffer,Gemeindename,BFS-Nr,Kantonskürzel,E,N,Sprache
0,Lausanne 25,1000,25,Lausanne,5586,VD,542094.8938,157051.9666,fr
1,Lausanne 26,1000,26,Lausanne,5586,VD,543068.1153,156403.0412,fr
2,Lausanne 27,1000,27,Lausanne,5586,VD,541921.1403,154775.3096,fr
3,Lausanne,1003,0,Lausanne,5586,VD,537956.7751,152398.2869,fr
4,Lausanne,1004,0,Lausanne,5586,VD,537089.8121,153349.5648,fr
...,...,...,...,...,...,...,...,...,...
4123,Unterwasser,9657,0,Wildhaus-Alt St. Johann,3359,SG,741690.2129,229037.4686,de
4124,Wildhaus,9658,0,Wildhaus-Alt St. Johann,3359,SG,744861.3314,229854.4341,de
4125,Thunersee,9999,1,Thunersee,9073,BE,621181.5226,170794.5768,de
4126,Brienzersee,9999,2,Brienzersee,9089,BE,640930.6820,175395.8963,de
4127,Bielersee,9999,0,Bielersee (BE),9149,BE,580261.9545,215168.9479,de

In [153]:
inbound_comm = pd.read_excel('../Data/Raw/inbound_comm.xlsx')
inbound_comm

,Zupendlerquote 2000,Unnamed: 1,3561
0,NaN,NaN,NaN
1,NaN,NaN,Anteil der zupendelnden Erwerbstätigen an den ...
2,Regions-ID,Regionsname,NaN
3,NaN,NaN,NaN
4,NaN,Schweiz,58.882161
...,...,...,...
2907,"11 - Mobilität, Verkehr > Pendlermobilität > ...",NaN,NaN
2908,Schweiz / Politische Gemeinden / 5.12.2000,NaN,NaN
2909,NaN,NaN,NaN
2910,Kontakt: statatlas@bfs.admin.ch,NaN,NaN
2911,"© Bundesamt für Statistik, ThemaKart, Neuchâte...",NaN,NaN

In [154]:
outbound_comm = pd.read_excel('../Data/Raw/outbound_comm.xlsx')
outbound_comm

,Wegpendlerquote 2000,Unnamed: 1,3581
0,NaN,NaN,NaN
1,NaN,NaN,Anteil der wegpendelnden Erwerbstätigen an den...
2,Regions-ID,Regionsname,NaN
3,NaN,NaN,NaN
4,NaN,Schweiz,57.259905
...,...,...,...
2907,"11 - Mobilität, Verkehr > Pendlermobilität > ...",NaN,NaN
2908,Schweiz / Politische Gemeinden / 5.12.2000,NaN,NaN
2909,NaN,NaN,NaN
2910,Kontakt: statatlas@bfs.admin.ch,NaN,NaN
2911,"© Bundesamt für Statistik, ThemaKart, Neuchâte...",NaN,NaN

In [22]:
# mminfo("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Distanz_CH_2337.mtx") # not working at the moment

In [23]:
# sc.read("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Reisezeit_CH_2337.mtx") # not working at the moment

In [155]:
dist_st = pd.read_table("../Data/Raw/DWV_2017_Strasse_Distanz_CH_2337.mtx", encoding="latin-1")
dist_st

             $O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [156]:
time_st = pd.read_table("../Data/Raw/DWV_2017_Strasse_Reisezeit_CH_2337.mtx", encoding="latin-1")
time_st

             $O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [157]:
dist_pt = pd.read_table("../Data/Raw/DWV_2017_ÖV_Distanz_CH_2337.mtx", encoding="latin-1")
dist_pt

             $O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [158]:
time_pt = pd.read_table("../Data/Raw/DWV_2017_ÖV_Reisezeit_CH_2337.mtx", encoding="latin-1")
time_pt

             $O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

## **5. Transforming Data**

### **5.1 Distance + time matrices**

**5.1.1 Street distance**

delete the leading 6 header rows

In [28]:
dist_st.drop(dist_st.index[0:7], inplace=True)
dist_st

                                 $O;D3
7                 1          1  5.326
8                 1          2  5.948
9                 1          3  9.613
10                1          4  8.669
11                1          5  8.191
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [29]:
dist_st = dist_st["$O;D3"].str.split(expand=True)

In [30]:
dist_st.loc[dist_st[1] == "Netzobjektnamen"]

         0                1     2
5461576  *  Netzobjektnamen  None

In [31]:
dist_st = dist_st.iloc[:5461569, : ]

In [32]:
dist_st.rename(columns = {0: "from", 1: "to", 2: "dist_street"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [33]:
dist_st

         from    to dist_street
7           1     1       5.326
8           1     2       5.948
9           1     3       9.613
10          1     4       8.669
11          1     5       8.191
...       ...   ...         ...
5461571  7301  7009     200.735
5461572  7301  7010     204.878
5461573  7301  7011     205.223
5461574  7301  7101     278.181
5461575  7301  7301       2.754

[5461569 rows x 3 columns]

**5.1.2 Street time**

In [34]:
time_st.iloc[0:8]

                                         $O;D3
0                                    * Von Bis
1                                    0000 0000
2                                     * Faktor
3                                         1.00
4                                          *
5  * Bundesamt für Raumentwicklung ARE Ittigen
6                                   * 18.03.20
7                         1          1 14.342

delete the leading 6 header rows

In [35]:
time_st.drop(time_st.index[0:7], inplace=True)
time_st

                                 $O;D3
7                 1          1 14.342
8                 1          2 15.830
9                 1          3 20.440
10                1          4 20.096
11                1          5 20.371
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [36]:
time_st = time_st["$O;D3"].str.split(expand=True)
time_st

            0   1       2
7           1   1  14.342
8           1   2  15.830
9           1   3  20.440
10          1   4  20.096
11          1   5  20.371
...       ...  ..     ...
5463910  7009  ""    None
5463911  7010  ""    None
5463912  7011  ""    None
5463913  7101  ""    None
5463914  7301  ""    None

[5463908 rows x 3 columns]

In [37]:
time_st.loc[time_st[1] == "Netzobjektnamen"]

         0                1     2
5461576  *  Netzobjektnamen  None

In [38]:
time_st = time_st.iloc[:5461569, : ]

In [39]:
time_st.rename(columns = {0: "from", 1: "to", 2: "time_street"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [40]:
time_st

         from    to time_street
7           1     1      14.342
8           1     2      15.830
9           1     3      20.440
10          1     4      20.096
11          1     5      20.371
...       ...   ...         ...
5461571  7301  7009     133.474
5461572  7301  7010     135.730
5461573  7301  7011     140.941
5461574  7301  7101     218.801
5461575  7301  7301       7.805

[5461569 rows x 3 columns]

**5.1.3 public transport time**

In [41]:
time_pt.iloc[0:8]

                                         $O;D3
0                                    * Von Bis
1                                    0000 0000
2                                     * Faktor
3                                         1.00
4                                          *
5  * Bundesamt für Raumentwicklung ARE Ittigen
6                                   * 18.03.20
7                         1          1 20.483

delete the leading 6 header rows

In [42]:
time_pt.drop(time_pt.index[0:7], inplace=True)
time_pt

                                 $O;D3
7                 1          1 20.483
8                 1          2 24.290
9                 1          3 42.945
10                1          4 36.187
11                1          5 37.729
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [43]:
time_pt = time_pt["$O;D3"].str.split(expand=True)
time_pt

            0   1       2
7           1   1  20.483
8           1   2  24.290
9           1   3  42.945
10          1   4  36.187
11          1   5  37.729
...       ...  ..     ...
5463910  7009  ""    None
5463911  7010  ""    None
5463912  7011  ""    None
5463913  7101  ""    None
5463914  7301  ""    None

[5463908 rows x 3 columns]

In [44]:
time_pt.loc[time_pt[1] == "Netzobjektnamen"]

         0                1     2
5461576  *  Netzobjektnamen  None

In [45]:
time_pt = time_pt.iloc[:5461569, : ]

In [46]:
time_pt.rename(columns = {0: "from", 1: "to", 2: "time_pt"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [47]:
time_pt

         from    to  time_pt
7           1     1   20.483
8           1     2   24.290
9           1     3   42.945
10          1     4   36.187
11          1     5   37.729
...       ...   ...      ...
5461571  7301  7009  302.505
5461572  7301  7010  310.881
5461573  7301  7011  319.149
5461574  7301  7101  275.675
5461575  7301  7301   14.917

[5461569 rows x 3 columns]

**5.1.4 public transport distance**

In [48]:
dist_pt.iloc[0:8]

                                         $O;D3
0                                    * Von Bis
1                                    0000 0000
2                                     * Faktor
3                                         1.00
4                                          *
5  * Bundesamt für Raumentwicklung ARE Ittigen
6                                   * 18.03.20
7                         1          1  4.183

delete the leading 6 header rows

In [49]:
dist_pt.drop(dist_pt.index[0:7], inplace=True)
dist_pt

                                 $O;D3
7                 1          1  4.183
8                 1          2  6.062
9                 1          3 11.986
10                1          4  9.970
11                1          5  8.778
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [50]:
dist_pt = dist_pt["$O;D3"].str.split(expand=True)
dist_pt

            0   1       2
7           1   1   4.183
8           1   2   6.062
9           1   3  11.986
10          1   4   9.970
11          1   5   8.778
...       ...  ..     ...
5463910  7009  ""    None
5463911  7010  ""    None
5463912  7011  ""    None
5463913  7101  ""    None
5463914  7301  ""    None

[5463908 rows x 3 columns]

In [51]:
dist_pt.loc[dist_pt[1] == "Netzobjektnamen"]

         0                1     2
5461576  *  Netzobjektnamen  None

In [52]:
dist_pt = dist_pt.iloc[:5461569, : ]

In [53]:
dist_pt.rename(columns = {0: "from", 1: "to", 2: "dist_pt"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [54]:
dist_pt

         from    to  dist_pt
7           1     1    4.183
8           1     2    6.062
9           1     3   11.986
10          1     4    9.970
11          1     5    8.778
...       ...   ...      ...
5461571  7301  7009  257.160
5461572  7301  7010  253.233
5461573  7301  7011  256.255
5461574  7301  7101  242.097
5461575  7301  7301    0.229

[5461569 rows x 3 columns]

**5.1.5 Joining distance tables**

In [55]:
dist = dist_st

In [56]:
dist_st["dist_pt"] = dist_pt["dist_pt"]

In [57]:
dist_st["time_st"] = time_st["time_street"]

In [58]:
dist_st["time_pt"] = time_pt["time_pt"]

In [59]:
dist

         from    to dist_street  dist_pt  time_st  time_pt
7           1     1       5.326    4.183   14.342   20.483
8           1     2       5.948    6.062   15.830   24.290
9           1     3       9.613   11.986   20.440   42.945
10          1     4       8.669    9.970   20.096   36.187
11          1     5       8.191    8.778   20.371   37.729
...       ...   ...         ...      ...      ...      ...
5461571  7301  7009     200.735  257.160  133.474  302.505
5461572  7301  7010     204.878  253.233  135.730  310.881
5461573  7301  7011     205.223  256.255  140.941  319.149
5461574  7301  7101     278.181  242.097  218.801  275.675
5461575  7301  7301       2.754    0.229    7.805   14.917

[5461569 rows x 6 columns]

**5.1.6 Write distance csv**

In [142]:
dist.to_csv("../Data/Cleaned/distances.csv")

### **5.2 Stop count list**

In [140]:
stop_count[:2]

  FP_ID,"TU_CODE","TU_BEZEICHNUNG","TU_ABKUERZUNG","FARTNUMMER","BPUIC","BP_BEZEICHNUNG","BP_ABKUERZUNG","KANTON","SLOID","VM_ART","FAHRTAGE","AB_ZEIT_KB","AN_ZEIT_KB","RICHTUNG_TEXT_AGGREGIERT","END_BP_BEZEICHNUNG","LINIE","BP_ID"
0  2022,"101","Verkehrsbetriebe Biel","VB-be",230...
1  2022,"101","Verkehrsbetriebe Biel","VB-be",230...

This table was not splitted when read. So it must be splitted, first after each ' " '

**5.2.1 Splitting stop count table**

In [109]:
stop_count_expand = stop_count.iloc[:,0].str.split(pat='"', expand=True) # 
stop_count_expand[:2]

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,"2022,",101,",",Verkehrsbetriebe Biel,",",VB-be,",23000,8504351,",Biel/Bienne Beaumont,",",,...,FUN,",",359,",01.01.1970 05:58:00,01.01.1970 05:58:00,",,",",Evilard/Leubringen,",",23,",138747"
1,"2022,",101,",",Verkehrsbetriebe Biel,",",VB-be,",23000,8504350,",Biel/Bienne Leubringenb.(Funi),",",,...,FUN,",",359,",01.01.1970 05:55:00,,",,",",Evilard/Leubringen,",",23,",123038"

Some columns contain only commas or are empty at all. These can be deleted in a next step.

**5.2.2 Deleting unneccessary columns**

In [110]:
stop_count_expand.drop([2, 4, 8, 9, 10, 12, 14, 16, 19, 20, 22], axis=1, inplace=True) # dropping comma and empty columns

**5.2.3 Renaming the columns**

In [111]:
stop_count_expand.rename(columns={0: "year", 1: "comp_Nr.", 3: "comp_name", 5: "comp_short", 6: "id_numbers", 7:"stat_name", 11: "canton", 13: "SLOID", 15: "tr_type", 17: "nr_days", 18: "schedule_time", 21: "end_st", 23: "line", 24:"BP_ID"}, inplace=True)
stop_count_expand[:2]

Now we see that there are many columns which must be cleaned in a next step. Some contains unneccessary commas, other must be splitted again.

**5.2.4 Cleaning all columns**

In [112]:
# column "year": contains unneccessary comma
stop_count_expand["year"] = stop_count_expand["year"].str.split(pat=',', expand=True)[0] # remove ","

In [114]:
# column "id_numbers": Contains two values, ride id and stop id, needs to be separated
stop_count_expand["ride_id"] = stop_count_expand["id_numbers"].str.split(pat=',', expand=True)[[1]] # first number is ride identification number
stop_count_expand["stop_id"] = stop_count_expand["id_numbers"].str.split(pat=',', expand=True)[[2]] # second number is stop identification number
stop_count_expand.drop("id_numbers", axis=1, inplace=True) # remove id_numbers column which is not needed anymore

In [117]:
# column "schedule_time": Contains Departure and arrival time, needs to be separated
stop_count_expand["arr_time"] = stop_count_expand["schedule_time"].str.split(pat=',', expand=True)[[1]] # first number is arrival
stop_count_expand["dep_time"] = stop_count_expand["schedule_time"].str.split(pat=',', expand=True)[[2]] # second number is departure
stop_count_expand.drop("schedule_time", axis=1, inplace=True) # remove id_numbers column which is not needed anymore

# only time is needed
stop_count_expand["arr_time"] = pd.to_datetime(stop_count_expand["arr_time"])
stop_count_expand["dep_time"] = pd.to_datetime(stop_count_expand["dep_time"])

In [137]:
# column "BP_ID": contains leading comma
stop_count_expand["BP_ID"] = stop_count_expand["BP_ID"].str.split(pat=',', expand=True)[0] # remove ","

In [138]:
stop_count_expand[:2]

,year,comp_Nr.,comp_name,comp_short,stat_name,canton,SLOID,tr_type,nr_days,end_st,line,BP_ID,ride_id,stop_id,arr_time,dep_time
0,2022,101,Verkehrsbetriebe Biel,VB-be,Biel/Bienne Beaumont,BE,ch:1:sloid:4351,FUN,359,Evilard/Leubringen,23,,23000,8504351,1970-01-01 05:58:00,1970-01-01 05:58:00
1,2022,101,Verkehrsbetriebe Biel,VB-be,Biel/Bienne Leubringenb.(Funi),BE,ch:1:sloid:4350,FUN,359,Evilard/Leubringen,23,,23000,8504350,1970-01-01 05:55:00,NaT

Now the table seems to be ok and can be written into a csv.

**5.2.5 Writing stop count csv**

In [141]:
stop_count_expand.to_csv("../Data/Cleaned/stop_count.csv")