## **1. Set connection to Google Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Change present working directory

In [ ]:
%cd /content/drive/MyDrive/MasterThesis

## **2. Git Handling**

In [ ]:
# !git config --global user.email "gabriel.peier@stud.hslu.ch"

In [ ]:
username = "Icelander169"
git_token = "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"
repository = "MasterThesis"

In [ ]:
# !git init Scripts

Initialized empty Git repository in /content/drive/MyDrive/MasterThesis/Scripts/.git/

In [ ]:
%cd Scripts

/content/drive/MyDrive/MasterThesis/Scripts

In [ ]:
!git status

On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   01_Reading_Data.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
!git add . # adding changes for commitment

In [ ]:
!git remote add origin https://{git_token}@github.com/{username}/{repository}.git
!git remote -v

origin	https://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@github.com/Icelander169/MasterThesis.git (fetch)
origin	https://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@github.com/Icelander169/MasterThesis.git (push)

In [ ]:
 !git commit -m "distance + time matrix integrated in data loading chapter"

[master 787a141] distance + time matrix integrated in data loading chapter
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 01_Reading_Data.ipynb (93%)

In [ ]:
!git push origin master

Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 1.67 KiB | 342.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/Icelander169/MasterThesis.git
   90bb5b0..787a141  master -> master

## **3. Importing packages**

In [ ]:
import pandas as pd
import numpy as np
# import scanpy as sc
from scipy.io import mminfo,mmread # handlings sparse matrices

## **4. Loading Data**

In [ ]:
ga_hta = pd.read_excel('/content/drive/My Drive/MasterThesis/Data/ga_hta_list.xlsx')
ga_hta

,Jahr_An_Anno,PLZ_NPA,GA_AG,GA_AG_flag,HTA_ADT_meta-prezzo,HTA_ADT_meta-prezzo_flag
0,2012,1000,72.0,NaN,976.0,NaN
1,2012,1003,744.0,NaN,3195.0,NaN
2,2012,1004,1919.0,NaN,8167.0,NaN
3,2012,1005,860.0,NaN,4021.0,NaN
4,2012,1006,1279.0,NaN,5366.0,NaN
...,...,...,...,...,...,...
28678,2020,9652,55.0,NaN,283.0,NaN
28679,2020,9655,12.7,1.0,95.0,NaN
28680,2020,9656,21.0,NaN,185.0,NaN
28681,2020,9657,36.0,NaN,235.0,NaN
28682,2020,9658,71.0,NaN,403.0,NaN

In [ ]:
population = pd.read_excel('/content/drive/My Drive/MasterThesis/Data/population.xlsx')
population

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,su-d-01.02.03.07,"Ständige Wohnbevölkerung nach Postleitzahl, Staatsangehörigkeitskategorie, Geschlecht, Fünfjahresaltersklasse und Zivilstand, am 31.12.2020",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,Postleitzahl,NaN,Staatsangehörigkeitskategorie,NaN,Geschlecht,NaN,Fünfjahresklasse,NaN,NaN,NaN,...,NaN,NaN,NaN,Zivilstand 1,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,Schweiz,Ausland,Mann,Frau,0-4,5-9,10-14,15-19,...,80-84,85-89,90 und mehr,Ledig,Verheiratet,Verwitwet,Geschieden,Unverheiratet,In eingetrage-ner Partner-schaft,Aufgelöste Partnerschaft
2,Schweiz,8670300,6459512,2210788,4302599,4367701,437118,439685,429468,420030,...,227086,147174,84029,3903333,3588894,403471,751735,617,19022,2981
3,1000,3991,2379,1612,1957,2034,208,179,219,559,...,50,27,14,2378,1307,81,217,0,7,1
4,1003,6528,3555,2973,3290,3238,265,187,190,206,...,85,55,56,4101,1628,178,556,1,59,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,1 Serienbruch ab 2014: Exkl. „ohne Angabe“,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3186,Quelle: STATPOP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3187,© BFS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3189,"Auskunft: Bundesamt für Statistik (BFS), Sekti...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
cars = pd.read_csv('/content/drive/My Drive/MasterThesis/Data/cars_per_municipality.csv', sep = ";", encoding = 'latin-1')
cars

,Gemeinde,Fahrzeuggruppe,Treibstoff,2015,2016,2017,2018,2019,2020,2021
0,1 Aeugst am Albis,Personenwagen,Benzin,845,822,815,816,809,804,792
1,1 Aeugst am Albis,Personenwagen,Diesel,288,306,316,318,326,329,320
2,1 Aeugst am Albis,Personenwagen,Benzin-elektrisch: Normal-Hybrid,13,18,16,20,22,30,43
3,1 Aeugst am Albis,Personenwagen,Benzin-elektrisch: Plug-in-Hybrid,0,1,2,7,7,12,20
4,1 Aeugst am Albis,Personenwagen,Diesel-elektrisch: Normal-Hybrid,0,0,2,2,3,2,5
...,...,...,...,...,...,...,...,...,...,...
151405,6810 La Baroche,Anhänger,Diesel-elektrisch: Plug-in-Hybrid,0,0,0,0,0,0,0
151406,6810 La Baroche,Anhänger,Elektrisch,0,0,0,0,0,0,0
151407,6810 La Baroche,Anhänger,Wasserstoff,0,0,0,0,0,0,0
151408,6810 La Baroche,Anhänger,Gas (mono- und bivalent),0,0,0,0,0,0,0
151409,6810 La Baroche,Anhänger,Anderer,180,190,202,202,209,216,227

In [ ]:
stations = pd.read_excel('/content/drive/My Drive/MasterThesis/Data/stations_list_bav.xlsx')
stations

,Dst-Nr85,Ld,Dst-Nr,KZ,Name,Länge,Name lang,Dst-Abk,BP,VP,...,Ortschaft,Gde-Nr,Gemeinde,Kt.,E-Koord.,N-Koord.,Höhe,Bemerkungen,Karte,Karte.1
0,N° sv.85,py,N° sv.,Cc,Nom (ordre alphab.),Longueur,Nom long,Sigle sv.,PE,PT,...,Localité,N° commune,Commune,Ct.,Coord. E,Coord. N,Altitude,Remarque,Carte,Carte
1,Dienststellen-\nNummer siebenstellig,Ländercode,Dienststellen-\nNummer (85...),Kontrollziffer (o.Ld),Name \n(Dst-Bezeichnung),Länge (Name),Name lang \n(50 Zeichen),Dienststellen-\nAbkürzung,Betriebspunkt des Fahrplans,Haltestelle,...,Ortschaft,Gemeinde-\nNummer BFS,Gemeinde,Kanton,E-Koordinate,N-Koordinate,Höhe m ü.M.,Bemerkungen,Hyperlink auf \nmapsearch.ch,Hyperlink auf \nmap.geo.admin.ch
2,NaN,NaN,NaN,NaN,"Datenstand am 24.02.2022, Auszug für 24.02.2022",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
3,8506013,85,6013,7,Aadorf,6,NaN,AD,*,Ho,...,Aadorf,4551,Aadorf,TG,2710378,1260736,528,NaN,▲,▲
4,8573363,85,73363,4,"Aadorf, Bahnhof",15,NaN,NaN,*,Ho,...,Aadorf,4551,Aadorf,TG,2710335,1260768,528,NaN,▲,▲
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
49999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
50001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲
50002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,▲,▲

In [ ]:
stop_count = pd.read_csv('/content/drive/My Drive/MasterThesis/Data/stop_count.csv', sep = ",", encoding="latin-1")
stop_count

        FP_ID,"TU_CODE","TU_BEZEICHNUNG","TU_ABKUERZUNG","FARTNUMMER","BPUIC","BP_BEZEICHNUNG","BP_ABKUERZUNG","KANTON","SLOID","VM_ART","FAHRTAGE","AB_ZEIT_KB","AN_ZEIT_KB","RICHTUNG_TEXT_AGGREGIERT","END_BP_BEZEICHNUNG","LINIE","BP_ID"
0        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
1        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
2        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
3        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
4        2022,"101","Verkehrsbetriebe Biel","VB-be",230...
...                                                    ...
1048570  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048571  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048572  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048573  2022,"764","Automobiles MBC","MBC Auto",4047,8...
1048574  2022,"764","Automobiles MBC","MBC Auto",4047,8...

[1048575 rows x 1 columns]

In [ ]:
town_directory = pd.read_csv('/content/drive/My Drive/MasterThesis/Data/town_directory.csv')
town_directory

,Ortschaftsname,PLZ,Zusatzziffer,Gemeindename,BFS-Nr,Kantonskürzel,E,N,Sprache
0,Lausanne 25,1000,25,Lausanne,5586,VD,542094.8938,157051.9666,fr
1,Lausanne 26,1000,26,Lausanne,5586,VD,543068.1153,156403.0412,fr
2,Lausanne 27,1000,27,Lausanne,5586,VD,541921.1403,154775.3096,fr
3,Lausanne,1003,0,Lausanne,5586,VD,537956.7751,152398.2869,fr
4,Lausanne,1004,0,Lausanne,5586,VD,537089.8121,153349.5648,fr
...,...,...,...,...,...,...,...,...,...
4123,Unterwasser,9657,0,Wildhaus-Alt St. Johann,3359,SG,741690.2129,229037.4686,de
4124,Wildhaus,9658,0,Wildhaus-Alt St. Johann,3359,SG,744861.3314,229854.4341,de
4125,Thunersee,9999,1,Thunersee,9073,BE,621181.5226,170794.5768,de
4126,Brienzersee,9999,2,Brienzersee,9089,BE,640930.6820,175395.8963,de
4127,Bielersee,9999,0,Bielersee (BE),9149,BE,580261.9545,215168.9479,de

In [ ]:
inbound_comm = pd.read_excel('/content/drive/My Drive/MasterThesis/Data/inbound_comm.xlsx')
inbound_comm

,Zupendlerquote 2000,Unnamed: 1,3561
0,NaN,NaN,NaN
1,NaN,NaN,Anteil der zupendelnden Erwerbstätigen an den ...
2,Regions-ID,Regionsname,NaN
3,NaN,NaN,NaN
4,NaN,Schweiz,58.882161
...,...,...,...
2907,"11 - Mobilität, Verkehr > Pendlermobilität > ...",NaN,NaN
2908,Schweiz / Politische Gemeinden / 5.12.2000,NaN,NaN
2909,NaN,NaN,NaN
2910,Kontakt: statatlas@bfs.admin.ch,NaN,NaN
2911,"© Bundesamt für Statistik, ThemaKart, Neuchâte...",NaN,NaN

In [ ]:
outbound_comm = pd.read_excel('/content/drive/My Drive/MasterThesis/Data/outbound_comm.xlsx')
outbound_comm

,Wegpendlerquote 2000,Unnamed: 1,3581
0,NaN,NaN,NaN
1,NaN,NaN,Anteil der wegpendelnden Erwerbstätigen an den...
2,Regions-ID,Regionsname,NaN
3,NaN,NaN,NaN
4,NaN,Schweiz,57.259905
...,...,...,...
2907,"11 - Mobilität, Verkehr > Pendlermobilität > ...",NaN,NaN
2908,Schweiz / Politische Gemeinden / 5.12.2000,NaN,NaN
2909,NaN,NaN,NaN
2910,Kontakt: statatlas@bfs.admin.ch,NaN,NaN
2911,"© Bundesamt für Statistik, ThemaKart, Neuchâte...",NaN,NaN

In [ ]:
# mminfo("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Distanz_CH_2337.mtx") # not working at the moment

In [ ]:
# sc.read("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Reisezeit_CH_2337.mtx") # not working at the moment

In [ ]:
dist_st = pd.read_table("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Distanz_CH_2337.mtx", encoding="latin-1")
dist_st

             $O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [ ]:
time_st = pd.read_table("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Reisezeit_CH_2337.mtx", encoding="latin-1")
time_st

             $O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [ ]:
dist_pt = pd.read_table("/content/drive/My Drive/MasterThesis/Data/DWV_2017_ÖV_Distanz_CH_2337.mtx", encoding="latin-1")
dist_pt

In [ ]:
time_pt = pd.read_table("/content/drive/My Drive/MasterThesis/Data/DWV_2017_ÖV_Reisezeit_CH_2337.mtx", encoding="latin-1")
time_pt